import React from 'react';
import { ArrowLeftIcon } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Footer } from '../components/Footer';
import { Navbar } from '../components/Navbar';

export function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[#f6f7fb] text-[#10111f]">
      <Navbar />

      <main className="px-5 pb-20 pt-28 sm:px-8 lg:px-10">
        <div className="mx-auto max-w-6xl">
          <div className="mb-6 flex items-center">
            <Link
              to="/"
              className="inline-flex items-center gap-2 rounded-full border border-[#dce4ef] bg-white/80 px-4 py-2 text-sm font-medium text-[#163437] transition hover:-translate-y-0.5 hover:bg-white"
            >
              <ArrowLeftIcon size={16} />
              Back to home
            </Link>
          </div>

          <div className="overflow-hidden rounded-[32px] border border-white/70 bg-white/80 shadow-[0_24px_80px_rgba(16,17,31,.08)] backdrop-blur">
            <div className="border-b border-[#e8eaf4] bg-gradient-to-r from-[#edf2ff] to-[#edfbf7] px-8 py-10 sm:px-10">
              <p className="mb-3 text-sm font-semibold uppercase tracking-[0.24em] text-[#4f46e5]">
                Legal
              </p>
              <h1 className="text-3xl font-semibold tracking-[-0.03em] text-[#10111f] sm:text-4xl">
                Privacy Policy
              </h1>
              <p className="mt-3 text-sm text-[#656a80]">Last updated: July 16, 2026</p>
              <p className="mt-4 max-w-3xl text-base leading-7 text-[#42505f]">
                This Privacy Policy describes our policies and procedures on the collection, use and disclosure of your information when you use the Service and tells you about your privacy rights and how the law protects you.
              </p>
            </div>

            <article className="space-y-8 px-8 py-10 text-[15px] leading-8 text-[#24313d] sm:px-10">
              <section>
                <h2 className="text-xl font-semibold text-[#10111f]">Interpretation and Definitions</h2>
                <h3 className="mt-4 text-lg font-semibold text-[#163437]">Interpretation</h3>
                <p>
                  The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or plural.
                </p>

                <h3 className="mt-5 text-lg font-semibold text-[#163437]">Definitions</h3>
                <p className="mt-2">For the purposes of this Privacy Policy:</p>
                <ul className="mt-4 list-disc space-y-3 pl-6">
                  <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                  <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where “control” means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                  <li><strong>Company</strong> refers to FrameDock, 633 W 5th Street, Los Angeles, CA 90012, USA.</li>
                  <li><strong>Cookies</strong> are small files placed on Your device by a website containing details of Your browsing history.</li>
                  <li><strong>Country</strong> refers to California, United States.</li>
                  <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
                  <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                  <li><strong>Service</strong> refers to the Website.</li>
                  <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
                  <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
                  <li><strong>Website</strong> refers to Framedock, accessible from <a href="https://framedock.one/" target="_blank" rel="noreferrer" className="font-medium text-[#4f46e5] underline decoration-[#4f46e5]/40 underline-offset-2">https://framedock.one/</a>.</li>
                  <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                </ul>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-[#10111f]">Collecting and Using Your Personal Data</h2>
                <h3 className="mt-4 text-lg font-semibold text-[#163437]">Types of Data Collected</h3>
                <h4 className="mt-3 font-semibold text-[#10111f]">Personal Data</h4>
                <p className="mt-2">
                  While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to, email address and first name and last name.
                </p>

                <h4 className="mt-4 font-semibold text-[#10111f]">Usage Data</h4>
                <p className="mt-2">
                  Usage Data is collected automatically when using the Service. It may include your device IP address, browser type and version, pages visited, time and date of visits, time spent on those pages, unique device identifiers and other diagnostic data.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-[#10111f]">Tracking Technologies and Cookies</h2>
                <p className="mt-3">
                  We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. These technologies may include cookies, browser cookies, web beacons, tags and scripts.
                </p>
                <p className="mt-3">
                  We use both Session and Persistent Cookies for essential, functionality and consent-related purposes. Where required by law, non-essential cookies are used only with your consent.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-[#10111f]">Use of Your Personal Data</h2>
                <p className="mt-3">
                  The Company may use Personal Data for the purpose of providing and maintaining the Service, managing your account, contacting you, providing marketing updates, managing requests, carrying out business transfers and improving the Service through analytics and trend analysis.
                </p>
                <p className="mt-3">
                  We may share your Personal Data with service providers, affiliates, business partners, other users or with your consent when necessary for the operation of the Service or as required by law.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-[#10111f]">Retention of Your Personal Data</h2>
                <p className="mt-3">
                  The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We may retain account information, support correspondence, analytics data and server logs for up to 24 months or longer where required for security, fraud prevention, or legal compliance.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-[#10111f]">Transfer of Your Personal Data</h2>
                <p className="mt-3">
                  Your information, including Personal Data, may be processed at the Company’s operating offices and in any other places where the parties involved in the processing are located. This means that information may be transferred to and maintained on computers located outside of your state, province, country or other governmental jurisdiction.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-[#10111f]">Delete Your Personal Data</h2>
                <p className="mt-3">
                  You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. You may update, amend or delete your information by signing in to your account or by contacting us.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-[#10111f]">Disclosure of Your Personal Data</h2>
                <p className="mt-3">
                  We may disclose your Personal Data in the good faith belief that such action is necessary to comply with a legal obligation, protect and defend the rights or property of the Company, prevent or investigate wrongdoing, protect personal safety or protect against legal liability.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-[#10111f]">Security of Your Personal Data</h2>
                <p className="mt-3">
                  The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-[#10111f]">Children’s Privacy</h2>
                <p className="mt-3">
                  Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If you are a parent or guardian and you are aware that your child has provided us with personal data, please contact us.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-[#10111f]">Links to Other Websites</h2>
                <p className="mt-3">
                  Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party’s site. We strongly advise you to review the Privacy Policy of every site you visit.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-[#10111f]">Changes to This Privacy Policy</h2>
                <p className="mt-3">
                  We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the “Last updated” date.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-[#10111f]">Contact Us</h2>
                <p className="mt-3">If you have any questions about this Privacy Policy, you can contact us:</p>
                <ul className="mt-4 list-disc space-y-2 pl-6">
                  <li>By email: connect@framedock.one</li>
                  <li>By visiting this page on our website: <a href="https://framedock.one" target="_blank" rel="noreferrer" className="font-medium text-[#4f46e5] underline decoration-[#4f46e5]/40 underline-offset-2">https://framedock.one</a></li>
                  <li>By phone: +1 (213) 555-2118</li>
                </ul>
              </section>
            </article>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
